### ISSUE TITLE
Building traverse-with-class-1.0.0.0 freezes on windows (ghc-8.6)

### ISSUE THREAD

**Issue by mvoidex** [feuerbach/traverse-with-class#11]
Copy of https://github.com/commercialhaskell/stackage/issues/4369

Building `traverse-with-class` freezes on Windows and only on `ghc-8.6`.

How to reproduce:

```
$ stack unpack traverse-with-class
$ cd traverse-with-class-1.0.0.0
$ stack build --resolver lts-12.26
...
ok!
$ stack build --resolver lts-13.7
...
[3 of 5] Compiling Data.Generics.Traversable.Instances ( Data\Generics\Traversable\Instances.hs, .stack-work\dist\e626a42b\build\Data\Generics\Traversable\Instances.o )
...freeze...
```

**Comment by feuerbach** [comment]
Yes, someone reported the same issue to me by email a few days ago.

This was my response:

> That's strange—it compiles fine here with 8.6.3. I'm using Linux, but I don't think that should make a difference.
> 
> One thing you could try is removing different instances in that module to figure out which ones cause this issue—maybe that will provide some insight. You could also try various ghc flags for debugging the compiler (they usually start with -d) to see what exactly ghc is doing.
> 
> I'm guessing the looping comes from the Template Haskell code; so you could insert some debug prints there to see what's causing it to loop.
> 
> Let me know what you find.

You might also want to report this as a ghc bug and see what they think.

**Comment by feuerbach** [comment]
As I learned from @nc6 and @TerrorJack, this is a known bug of ghc 8.6.3 on windows: https://ghc.haskell.org/trac/ghc/ticket/16071
